import type { SxProps, Theme } from "@mui/material";

export const messageBubbleStyles = {
  row: (isUser: boolean): SxProps<Theme> => ({
    flexDirection: "row",
    justifyContent: isUser ? "flex-end" : "flex-start",
    alignItems: "flex-end",
    gap: 1,
    mb: 1.5,
  }),
  avatar: {
    width: 32,
    height: 32,
    flexShrink: 0,
    color: "#fff",
    background: "linear-gradient(150deg, #aa3bff 0%, #7a1fd0 100%)",
  },
  column: (isUser: boolean): SxProps<Theme> => ({
    display: "flex",
    flexDirection: "column",
    alignItems: isUser ? "flex-end" : "flex-start",
    maxWidth: "78%",
  }),
  bubble: (isUser: boolean, isError: boolean): SxProps<Theme> => ({
    px: 1.75,
    py: 1,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomRightRadius: isUser ? 4 : 18,
    borderBottomLeftRadius: isUser ? 18 : 4,
    wordBreak: "break-word",
    whiteSpace: "pre-wrap",
    bgcolor: isError
      ? "error.main"
      : isUser
        ? "primary.main"
        : "background.paper",
    color: isError || isUser ? "#fff" : "text.primary",
    border: isUser || isError ? "none" : "1px solid",
    borderColor: "divider",
  }),
  cursor: {
    display: "inline-block",
    width: "2px",
    height: "1em",
    ml: "2px",
    bgcolor: "currentColor",
    verticalAlign: "text-bottom",
    animation: "fitmind-cursor-blink 1s step-start infinite",
    "@keyframes fitmind-cursor-blink": {
      "50%": { opacity: 0 },
    },
  },
  typingDots: {
    flexDirection: "row",
    alignItems: "center",
    gap: 0.5,
    py: 0.25,
  },
  dot: (delay: number): SxProps<Theme> => ({
    width: 6,
    height: 6,
    borderRadius: "50%",
    bgcolor: "text.disabled",
    animation: "fitmind-typing-bounce 1.2s ease-in-out infinite",
    animationDelay: `${delay}s`,
    "@keyframes fitmind-typing-bounce": {
      "0%, 60%, 100%": { transform: "translateY(0)", opacity: 0.5 },
      "30%": { transform: "translateY(-4px)", opacity: 1 },
    },
  }),
  timestamp: {
    mt: 0.25,
    mx: 0.5,
  },
  // Styles applied to rendered Markdown in assistant messages so headings,
  // lists, tables, and code look right inside the chat bubble.
  markdown: {
    whiteSpace: "normal",
    fontSize: "0.875rem",
    lineHeight: 1.55,
    "& > *:first-of-type": { mt: 0 },
    "& > *:last-child": { mb: 0 },
    "& p": { m: 0, mb: 1 },
    "& ul, & ol": { pl: 2.5, m: 0, mb: 1 },
    "& li": { mb: 0.25 },
    "& h1, & h2, & h3, & h4, & h5, & h6": {
      fontSize: "1rem",
      fontWeight: 700,
      mt: 1.5,
      mb: 0.5,
      lineHeight: 1.3,
    },
    "& a": { color: "primary.main", textDecoration: "underline" },
    "& code": {
      fontFamily: "ui-monospace, monospace",
      fontSize: "0.85em",
      bgcolor: "action.hover",
      px: 0.5,
      py: "1px",
      borderRadius: 0.5,
    },
    "& pre": {
      bgcolor: "action.hover",
      p: 1,
      borderRadius: 1,
      overflowX: "auto",
      my: 1,
    },
    "& pre code": { bgcolor: "transparent", p: 0 },
    "& blockquote": {
      borderLeft: "3px solid",
      borderColor: "divider",
      pl: 1.5,
      ml: 0,
      color: "text.secondary",
    },
    "& hr": { border: 0, borderTop: "1px solid", borderColor: "divider", my: 1 },
    "& table": {
      borderCollapse: "collapse",
      display: "block",
      overflowX: "auto",
      my: 1,
      fontSize: "0.85em",
    },
    "& th, & td": {
      border: "1px solid",
      borderColor: "divider",
      px: 1,
      py: 0.5,
      textAlign: "left",
    },
    "& th": { bgcolor: "action.hover", fontWeight: 700 },
    "& strong": { fontWeight: 700 },
  },
};
