/** All user-facing copy lives here so it stays consistent and easy to change. */
export const STRINGS = {
  app: {
    name: "FitMind AI",
    tagline: "Your AI-powered fitness coach",
    heroTitle: "Train smarter, not just harder",
    features: [
      "AI workout plans built around you",
      "Recovery-aware coaching that adapts",
      "Earn XP and level up as you train",
    ],
  },
  aria: {
    showPassword: "Show password",
    hidePassword: "Hide password",
  },
  login: {
    title: "Welcome back",
    subtitle: "Log in to continue your journey",
    submit: "Log in",
    submitting: "Logging in…",
    switchPrompt: "Don't have an account?",
    switchAction: "Sign up",
  },
  signup: {
    title: "Create your account",
    subtitle: "Start training smarter today",
    submit: "Sign up",
    submitting: "Creating account…",
    switchPrompt: "Already have an account?",
    switchAction: "Log in",
  },
  fields: {
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
  },
  validation: {
    emailRequired: "Email is required",
    emailInvalid: "Enter a valid email address",
    passwordRequired: "Password is required",
    passwordTooShort: "Password must be at least 8 characters",
    passwordWeak: "Add upper, lower, number, or symbol to strengthen it",
    confirmRequired: "Please confirm your password",
    confirmMismatch: "Passwords do not match",
  },
  errors: {
    loginFailed: "Could not log in. Check your credentials and try again.",
    signupFailed: "Could not create your account. Please try again.",
    network: "Cannot reach the server. Is the backend running?",
    generic: "Something went wrong. Please try again.",
  },
  toast: {
    loggedIn: "Welcome back!",
    signedUp: "Account created!",
    loggedOut: "You have been logged out",
  },
  passwordStrength: {
    label: "Password strength",
    levels: ["Too weak", "Weak", "Fair", "Good", "Strong"],
  },
  nav: {
    dashboard: "Dashboard",
    workouts: "Workouts",
    recovery: "Recovery",
    voiceCheckin: "Voice Check-in",
    nutrition: "Nutrition",
    gamification: "Gamification",
    friends: "Friends",
    profile: "Profile",
    settings: "Settings",
  },
  navbar: {
    openMenuAria: "Open navigation menu",
    notificationsAria: "Notifications",
    accountAria: "Account menu",
    signedInAs: "Signed in as",
    logout: "Log out",
  },
  dashboard: {
    welcome: (name: string) => `Welcome back, ${name}!`,
    subtitle: "Here's your training snapshot for today.",
    stats: {
      xp: "XP",
      level: "Level",
      streak: "Day streak",
      workoutsToday: "Workouts today",
    },
    quickActions: "Quick actions",
    actions: {
      startWorkout: "Start a workout",
      logRecovery: "Recovery check",
      voiceCheckin: "Voice check-in",
      viewProfile: "View profile",
    },
    loadError: "Could not load your dashboard. Please try again.",
  },
  comingSoon: {
    badge: "Coming soon",
    description: (feature: string) =>
      `${feature} is under construction — it will arrive in a future update.`,
  },
  recovery: {
    title: "Recovery",
    subtitle: "Log how you feel and get today's training guidance.",
    form: {
      title: "Today's check-in",
      sleepHours: "Sleep hours",
      sleepQuality: "Sleep quality",
      stressLevel: "Stress level",
      muscleSoreness: "Muscle soreness",
      qualityHint: "1 = terrible · 5 = excellent",
      stressHint: "1 = calm · 5 = very stressed",
      sorenessHint: "1 = none · 5 = very sore",
      submit: "Log recovery",
      submitting: "Scoring…",
      success: "Recovery logged!",
      error: "Could not log your recovery. Please try again.",
      alreadyDoneTitle: "Today's check-in is done ✅",
      alreadyDoneBody: "Your recovery score is in — come back tomorrow morning.",
    },
    score: {
      title: "Today's recovery",
      outOf: "/ 100",
      error: "Could not load your recovery score.",
    },
    history: {
      title: "Last 14 days",
      empty: "Log a few check-ins to see your trend here.",
      error: "Could not load recovery history.",
      tooltipLabel: "Score",
    },
  },
  voiceCheckin: {
    title: "Voice Check-in",
    subtitle: "Tell us how you're feeling — we'll analyse your mood and energy.",
    recorder: {
      title: "How are you feeling today?",
      hint: "Tap the mic and speak for a few seconds.",
      promptLabel: "Say something like:",
      promptTexts: [
        "“Today I'm feeling ____, my energy is ____ out of ten, I slept ____ hours, and my body feels ____.”",
        "“I woke up feeling ____ this morning. My energy level is about ____ out of ten, and my muscles feel ____.”",
        "“Right now my mood is ____. I slept ____ hours last night, my stress is ____, and I'm feeling ____ about training today.”",
        "“Honestly, today I feel ____. Energy-wise I'd say ____ out of ten. Yesterday's workout left me feeling ____.”",
        "“My day has been ____ so far. I'm feeling ____ mentally, my body feels ____, and my motivation to train is ____.”",
        "“This week has felt ____. Today specifically I'm ____, my sleep was ____, and my energy sits around ____ out of ten.”",
      ],
      startAria: "Start recording",
      stopAria: "Stop recording and analyse",
      recording: "Recording…",
      uploading: "Analysing your check-in…",
      permissionDenied:
        "Microphone access was denied. Allow it in your browser settings and try again.",
      noMicrophone: "No microphone found. Connect one and try again.",
      notSupported: "Audio recording isn't supported in this browser.",
      error: "Could not process your check-in. Please try again.",
      success: "Check-in analysed!",
    },
    result: {
      title: "Your latest check-in",
      energyLabel: "Energy level",
      energyOutOf: "/ 10",
      transcriptLabel: "What you said",
      emptyTranscript: "(no speech detected)",
    },
    history: {
      chartTitle: "Mood & energy trend",
      listTitle: "Recent check-ins",
      empty: "No check-ins yet — record your first one!",
      error: "Could not load your check-in history.",
      tooltipEnergy: "Energy",
    },
    moods: {
      positive: "Positive",
      neutral: "Neutral",
      low: "Low",
    },
  },
  workout: {
    title: "Workouts",
    subtitle: "Your AI-generated weekly training plan.",
    generate: "Generate new plan",
    generating: "Generating your plan…",
    generateHint: "Built from your goal, equipment, recovery and mood.",
    generated: "New weekly plan ready!",
    generateError: "Could not generate a plan. Please try again.",
    planError: "Could not load your weekly plan.",
    noPlanTitle: "No plan yet",
    noPlanBody: "Generate your first AI workout plan to get started.",
    today: {
      title: "Today's workout",
      restDay: "Rest day — no exercises today. Recover well!",
      error: "Could not load today's workout.",
      progress: (done: number, total: number) => `${done}/${total} sets`,
      celebration: "Workout complete! 🎉",
      finish: "Finish workout",
      alreadyDoneTitle: "Today's workout is logged 💪",
      alreadyDoneBody: "Great work! Come back tomorrow for your next session.",
    },
    timer: {
      start: "Start workout",
      pause: "Pause",
      resume: "Resume",
    },
    logger: {
      setLabel: (n: number) => `Set ${n}`,
      setAria: (exercise: string, set: number) => `Mark ${exercise} set ${set} done`,
      exerciseDone: "Done 💪",
    },
    completion: {
      title: "Workout complete",
      summaryTitle: "Summary",
      durationLabel: "Duration",
      intensityLabel: "How intense was it?",
      intensities: {
        low: "Low",
        medium: "Medium",
        high: "High",
      },
      setsDone: (done: number, total: number) => `${done}/${total} sets`,
      save: "Save workout",
      saving: "Saving…",
      saved: "Workout saved!",
      saveError: "Could not save your workout. Please try again.",
      xpEarned: (xp: number) => `+${xp} XP`,
      totalXp: (xp: number) => `Total: ${xp} XP`,
      levelUp: (level: number) => `Level up! You're now level ${level} 🎉`,
      newBadge: (badge: string) => `New badge: ${badge}`,
      done: "Done",
    },
    week: {
      title: "This week",
      exercisesCount: (count: number) =>
        count === 1 ? "1 exercise" : `${count} exercises`,
    },
    exercise: {
      setsReps: (sets: number, reps: string) => `${sets} × ${reps}`,
      restLabel: "Rest",
      videoAria: "Watch exercise video",
      doneAria: (name: string) => `Mark ${name} as done`,
    },
    history: {
      title: "History",
      streak: (days: number) => (days === 1 ? "1-day streak" : `${days}-day streak`),
      completedOn: "Workout completed 💪",
      nothingOn: "Nothing logged on this day.",
      hint: "Completed workouts light up here once you start logging (Day 8).",
      weekdays: ["M", "T", "W", "T", "F", "S", "S"],
    },
    types: {
      strength: "Strength",
      cardio: "Cardio",
      flexibility: "Flexibility",
      rest: "Rest",
      other: "Training",
    },
  },
  nutrition: {
    title: "Nutrition",
    subtitle: "Track your meals, macros and hydration for today.",
    summaryError: "Could not load today's nutrition.",
    form: {
      title: "Add a meal",
      name: "Meal name",
      calories: "Calories (kcal)",
      protein: "Protein (g)",
      carbs: "Carbs (g)",
      fats: "Fats (g)",
      mealType: "Meal type",
      estimate: (kcal: number) => `≈ ${kcal} kcal from macros`,
      useEstimate: "Use estimate",
      submit: "Log meal",
      submitting: "Logging…",
      success: "Meal logged!",
      xpToast: (xp: number) => `+${xp} XP`,
      levelUpToast: (level: number) => `Level up! You're now level ${level} 🎉`,
      error: "Could not log your meal. Please try again.",
      validation: {
        nameRequired: "Enter a meal name",
        caloriesRequired: "Enter calories (0 or more)",
        macroInvalid: "Must be 0 or more",
      },
    },
    mealTypes: {
      breakfast: "Breakfast",
      lunch: "Lunch",
      dinner: "Dinner",
      snack: "Snack",
    },
    calories: {
      title: "Daily calories",
      progress: (eaten: number, goal: number) => `${eaten} / ${goal} kcal`,
      remaining: (kcal: number) => `${kcal} kcal remaining`,
      over: (kcal: number) => `${kcal} kcal over goal`,
    },
    macros: {
      title: "Macro split",
      empty: "Log a meal to see your macro breakdown.",
      labels: {
        protein: "Protein",
        carbs: "Carbs",
        fats: "Fats",
      },
      legendItem: (label: string, percent: number, grams: number) =>
        `${label} ${percent}% · ${grams}g`,
    },
    water: {
      title: "Water intake",
      goal: (glasses: number, goalGlasses: number, ml: number) =>
        `${glasses}/${goalGlasses} glasses · ${ml} ml`,
      addAria: "Add a glass of water",
      removeAria: "Remove a glass of water",
      goalReached: "Hydration goal reached! 💧",
      error: "Could not update water intake.",
    },
    history: {
      title: "Today's meals",
      empty: "No meals logged yet today.",
      macros: (protein: number, carbs: number, fats: number) =>
        `P ${protein}g · C ${carbs}g · F ${fats}g`,
      kcal: (kcal: number) => `${kcal} kcal`,
    },
  },
  gamification: {
    title: "Gamification",
    subtitle: "Your XP, streaks and badges — keep the momentum going.",
    loadError: "Could not load your gamification profile.",
    level: {
      title: (level: number) => `Level ${level}`,
      maxTitle: "Max level reached!",
      xpToNext: (xp: number) => `${xp} XP to next level`,
      totalXp: (xp: number) => `${xp} total XP`,
    },
    xpBar: {
      ariaLabel: "XP progress to next level",
    },
    streak: {
      title: "Streaks",
      current: "Current streak",
      longest: "Longest streak",
      days: (n: number) => (n === 1 ? "1 day" : `${n} days`),
    },
    badges: {
      title: "Badges",
      earnedCount: (earned: number, total: number) => `${earned}/${total} earned`,
      locked: "Locked",
      earnedOn: (date: string) => `Earned ${date}`,
      newBadgeToast: (name: string) => `New badge unlocked: ${name}! 🎉`,
      newBadgeChip: "New!",
      howToUnlock: "How to unlock",
      close: "Close",
    },
  },
} as const;
